/**
 * Generates the index HTML page
 * @param {*} date 
 * @param {*} server_port 
 * @returns 
 */
exports.genIndexPage = function (date, server_port) {
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>About People...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-deep-purple">
            <h1><td>About People</td></h1>
        </header>
    
        <div class="w3-container">
            <ol>
                <li>
                    <a href="http://localhost:${server_port}/pessoas">
                        List people
                    </a>
                </li>
                <li>
                    <a href="http://localhost:${server_port}/genderDist">
                        Gender Distribution
                    </a>
                </li>
            </ol>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas_server: ${date}</h5>
        </footer>
    </div>
    </body>
</html>
`

    return pagHTML
}

/**
 * Generates the HTML page with the list of people
 * @param {*} people_list 
 * @param {*} date 
 * @param {*} SERVER_PORT 
 * @returns 
 */
exports.genPeoplePage = function (people_list, date, SERVER_PORT) {
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>About People...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-deep-purple">
            <h1>People List (${people_list.length})</h1>
        </header>
    
        <div class="w3-container">
            <a name="top"></a>
            <table class="w3-table-all w3-hoverable">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
`
    // Generates table rows with people links
    for (i = 0; i < people_list.length; i++) {
        pagHTML +=
`                
                <tr>
                    <td>
                        <a href="http://localhost:${SERVER_PORT}/pessoas/${people_list[i].id}">
                            ${people_list[i].nome}</td>
                        </a>
                </tr>       
`
    }

pagHTML += 
`
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by people_server: ${date}</h5>
            <h6>[<a href="#top">Back to top</a>]</h6>
            <h6>[<a href="http://localhost:${SERVER_PORT}/">Back to index</a>]</h6>
        </footer>
    </div>
    </body>
</html>
`

    return pagHTML
}

/**
 * Generates the HTML page for a person
 * @param {*} person 
 * @param {*} date 
 * @param {*} SERVER_PORT 
 * @returns 
 */
exports.genPersonPage = function (person, date, SERVER_PORT) {
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>About People...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-deep-purple">
            <h1><td>${person.nome}</td></h1>
        </header>
    
        <div class="w3-container">
`

pagHTML += 
`
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by people_server: ${date}</h5>
            <h6>[<a href="http://localhost:${SERVER_PORT}/">Back to index</a>]</h6>
        </footer>
    </div>
    </body>
</html>
`

    return pagHTML
}

/**
 * Generates the HTML page for the gender distribution
 * @param {*} distribution 
 * @param {*} date 
 * @param {*} SERVER_PORT 
 * @returns 
 */
exports.genGenderDistPage = function (distribution, date, SERVER_PORT) {
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>About People...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">

        <header class="w3-container w3-deep-purple">
            <h1><td>Gender Distribuition</td></h1>
        </header>
    
        <div class="w3-container">
            <table class="w3-table-all w3-hoverable">
                <tr>
                    <th>Gender</th>
                    <th>Nº of People</th>
                </tr>
                <tr>
                    <td>Female</td>
                    <td>${distribution.f}</td>
                </tr>
                <tr>
                    <td>Male</td>
                    <td>${distribution.m}</td>
                </tr>
                <tr>
                    <td>Other</td>
                    <td>${distribution.o}</td>
                </tr>
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by people_server: ${date}</h5>
            <h6>[<a href="http://localhost:${SERVER_PORT}/">Back to index</a>]</h6>
        </footer>
    </div>
    </body>
</html>
`

    return pagHTML
}

