version: '1'
services:
  data_api:
    container_name: data_api
    build: ./data_api
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/EMD
      - PORT=7001
    ports:
      - "13001:7001"
    depends_on:
      - mongodb
    networks:
      - afericao_net

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "13002:27017"
    volumes:
      - ./import_data.sh:/import_data.sh
      - ./emd.json:/emd.json
    networks:
      - afericao_net
networks:
  afericao_net:
    driver: bridge

volumes:
  mongodata:
    driver: local