version: '3.1'
services:
  interface:
    container_name: interface
    build: ./Interface
    restart: always
    environment:
      - API_URL=http://data_api:7001
      - PORT=7000
    ports:
      - "13000:7000"
    networks:
      - afericao_net

  data_api:
    container_name: data_api
    build: ./API
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/EMD
      - PORT=7001
    ports:
      - "13001:7001"
    depends_on:
      - mongodb
    networks:
      - afericao_net

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "13002:27017"
    networks:
      - afericao_net
    volumes:
      - mongodata:/data/db
      - ./datasets:/datasets
networks:
  afericao_net:
    driver: bridge

volumes:
  mongodata:
    driver: local